import React from 'react';
import { AlertTriangle, Stethoscope, Scale, HelpCircle, Info, PhoneCall } from 'lucide-react';

const sections = [
  {
    icon: <Info size={22} />,
    title: 'For Informational Purposes Only',
    body: `The Plant Disease Detector is an educational and informational tool designed to assist farmers, students, and gardeners in identifying potential plant diseases. The diagnoses, treatment recommendations, and information provided by this application are generated by an AI model and are intended for general informational purposes only.`
  },
  {
    icon: <Stethoscope size={22} />,
    title: 'Not a Substitute for Professional Advice',
    body: `The information provided by this application does not constitute professional agricultural, horticultural, or scientific advice. The AI-generated diagnoses may not be 100% accurate. For critical crop management decisions, significant financial investments, or large-scale agricultural operations, always consult a certified plant pathologist, local agricultural extension officer, or qualified agronomist.`
  },
  {
    icon: <AlertTriangle size={22} />,
    title: 'Accuracy Limitations',
    body: `While we strive to provide accurate and up-to-date information, the AI model may make errors or misidentify diseases — particularly when image quality is poor, the disease is in an early stage, or when multiple overlapping conditions are present. The confidence level shown is an estimate, not a guarantee.`
  },
  {
    icon: <Scale size={22} />,
    title: 'Chemical Treatment Disclaimer',
    body: `Any chemical treatment recommendations provided are for general guidance only. Always read and follow the complete label instructions of any pesticide or chemical product before use. Ensure compliance with local regulations regarding chemical usage. Improper use of agricultural chemicals can be hazardous to human health, animals, and the environment.`
  },
  {
    icon: <HelpCircle size={22} />,
    title: 'No Liability',
    body: `The developers, students, and institution associated with the Plant Disease Detector project shall not be held liable for any crop loss, financial damage, health issues, or environmental harm resulting from reliance on the information provided by this application. Use this tool as one of several resources — not as a sole source of decision-making.`
  },
  {
    icon: <PhoneCall size={22} />,
    title: 'When to Seek Expert Help',
    body: `If your crop is showing severe symptoms, if the disease is spreading rapidly, if you are dealing with a notifiable plant disease, or if you have any doubts about the diagnosis, please immediately contact your local agricultural department, Krishi Vigyan Kendra (KVK), or a professional plant pathologist.`
  },
];

export default function DisclaimerPage() {
  return (
    <div className="static-page animate-fade-in">
      <div className="static-page-hero disclaimer-hero">
        <div className="static-page-hero-icon"><AlertTriangle size={40} color="white" /></div>
        <h1 className="static-page-title">Disclaimer</h1>
        <p className="static-page-subtitle">
          Please read this disclaimer carefully before using the Plant Disease Detector.
        </p>
        <p className="static-page-meta">Last updated: May 2026</p>
      </div>

      <div className="static-sections">
        {sections.map((s, i) => (
          <div className="static-section" key={i}>
            <div className="static-section-header">
              <div className="static-section-icon disclaimer-icon">{s.icon}</div>
              <h2 className="static-section-title">{s.title}</h2>
            </div>
            <p className="static-section-body">{s.body}</p>
          </div>
        ))}
      </div>

      <div className="disclaimer-notice">
        <AlertTriangle size={20} />
        <span>
          This tool is a <strong>Mini Project</strong> developed by B.Tech CSE students at Vignan Institute of Management and Technology for Women (2023–2027).
          It is meant for educational purposes and academic demonstration.
        </span>
      </div>
    </div>
  );
}
